events{
    workers_connections 1024;
}

http {

    log_format upstreamlog '$remote_addr - $host [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$upstream_addr"';
    access_log /var/log/nginx/access.log upstreamlog;

    upstream edge_servers{
        server backend-1:3000 max_fails=3 fail_timeout=3s;
        server backend-2:3000 max_fails=3 fail_timeout=3s;
        server backend-3:3000 max_fails=3 fail_timeout=3s;  
        keepalive 256      
    }

}