services:

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      backend-1:
        condition: service_healthy
      backend-2:
        condition: service_healthy
      backend-3:
        condition: service_healthy                
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_net
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8081:80"
    networks:
      - app_net
  supervisor:
    build:
      context: .
      dockerfile: docker/supervisor/Dockerfile

    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:4000/health"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  simulador:
    build:
      context: .
      dockerfile: docker/simulador/Dockerfile
    networks:
      - app_net
    depends_on:
      backend-1:
        condition: service_healthy
      backend-2:
        condition: service_healthy
      backend-3:
        condition: service_healthy 

  backend-1:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    image: load-testing-platform-backend:local
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      INSTANCE_ID: backend-1
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "wget", "--spider","-q", "http://localhost:3000/health"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

  backend-2:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    image: load-testing-platform-backend:local
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      INSTANCE_ID: backend-2      
    depends_on:
      database:
        condition: service_healthy
      backend-1:
        condition: service_started  
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "wget", "--spider","-q", "http://localhost:3000/health"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

  backend-3:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    image: load-testing-platform-backend:local
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      INSTANCE_ID: backend-3
    depends_on:
      database:
        condition: service_healthy
      backend-1:
        condition: service_started  
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "wget", "--spider","-q", "http://localhost:3000/health"]
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app_net
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/database/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  db_data:
  
networks:
  app_net: